### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by christophercliff** [christophercliff/flatmarket-server-heroku#1]
The process fails to start and https://your-app.herokuapp.com/ shows the default Heroku error page.

**Comment by christophercliff** [comment]
This is likely caused by an invalid `CORS_ORIGINS` configuration. This field must be valid JSON or the process will crash. It should have the form:

```json
["https://your-website.com"]
```

Double quotes are required.

When the server is configured correctly, should return `{ status: "ok" }`. Example http://flatmarket.herokuapp.com/.

**Comment by andrewcoelho** [comment]
Getting this error:
{"code":"invalid_schema","message":"Invalid schema at \"https://kaventa.com/flatmarket.json\"."}

The schema was directly copy and pasted from the getting started guide so I'm not sure why this is happening.

**Comment by christophercliff** [comment]
If you run your schema document through https://github.com/christophercliff/flatmarket-schema it should give you a more detailed error.

**Comment by andrewcoelho** [comment]
I get null for the error when running it through that.

**Comment by christophercliff** [comment]
There might be something in your Heroku logs. If you're still stuck, you could also try running a server locally against your remote schema document, https://github.com/christophercliff/flatmarket-server#usage

**Comment by landestates** [comment]
fyi... 

the example needs to be updated 

{"code":"invalid_stripe_configuration","message":"Expired API Key provided: sk_test_********************DqnC"}

**Comment by karlderdmann** [comment]
fyi, would be interesting to see the example updated

{"code":"invalid_stripe_configuration","message":"Expired API Key provided: sk_test_********************DqnC"}
